<?php
"INSERT INTO `abilitys`
(`name_ability`, `description_ability`, `id_generation_ability`) VALUES 
('Stench', 'By releasing stench when attacking, this Pokémon may cause the target to flinch', 3),
('Drizzle', 'The Pokémon makes it rain when it enters a battle', 3),
('Speed Boost', 'Its Speed stat is boosted every turn', 3),
('Battle Armor', 'Hard armor protects the Pokémon from critical hits', 3),
('Sturdy', 'It cannot be knocked out with one hit. One-hit KO moves cannot knock it out, either', 3),
('Damp', 'Prevents the use of explosive moves such as Self-Destruct by dampening its surroundings', 3),
('Limber', 'Its limber body protects the Pokémon from paralysis', 3),
('Sand Veil', 'Boosts the Pokémon\'s evasion in a sandstorm', 3),
('Static', 'The Pokémon is charged with static electricity, so contact with it may cause paralysis', 3),
('Volt Absorb', 'Restores HP if hit by an Electric-type move, instead of taking damage', 3),
('Water Absorb', 'Restores HP if hit by a Water-type move, instead of taking damage', 3),
('Oblivious', 'The Pokémon is oblivious, and that keeps it from being infatuated or falling for taunts', 3),
('Cloud Nine', 'Eliminates the effects of weather', 3),
('Compound Eyes', 'The Pokémon\'s compound eyes boost its accuracy', 3),
('Insomnia', 'The Pokémon is suffering from insomnia and cannot fall asleep', 3),
('Color Change', 'The Pokémon\'s type becomes the type of the move used on it', 3),
('Immunity', 'The immune system of the Pokémon prevents it from getting poisoned', 3),
('Flash Fire', 'Powers up the Pokémon\'s Fire-type moves if it\'s hit by one', 3),
('Shield Dust', 'This Pokémon\'s dust blocks the additional effects of attacks taken', 3),
('Own Tempo', 'This Pokémon has its own tempo, and that prevents it from becoming confused', 3),
('Suction Cups', 'This Pokémon uses suction cups to stay in one spot to negate all moves and items that force switching out', 3),
('Intimidate', 'The Pokémon intimidates opposing Pokémon upon entering battle, lowering their Attack stat', 3),
('Shadow Tag', 'This Pokémon steps on the opposing Pokémon\'s shadow to prevent it from escaping', 3),
('Rough Skin', 'This Pokémon inflicts damage with its rough skin to the attacker on contact', 3),
('Wonder Guard', 'Its mysterious power only lets supereffective moves hit the Pokémon', 3),
('Levitate', 'By floating in the air, the Pokémon receives full immunity to all Ground-type moves', 3),
('Effect Spore', 'Contact with the Pokémon may inflict poison, sleep, or paralysis on its attacker', 3),
('Synchronize', 'The attacker will receive the same status condition if it inflicts a burn, poison, or paralysis to the Pokémon', 3),
('Clear Body', 'Prevents other Pokémon\'s moves or Abilities from lowering the Pokémon\'s stats', 3),
('Natural Cure', 'All status conditions heal when the Pokémon switches out', 3),
('Lightning Rod', 'The Pokémon draws in all Electric-type moves. Instead of being hit by Electric-type moves, it boosts its Sp. Atk', 3),
('Serene Grace', 'Boosts the likelihood of additional effects occurring when attacking', 3),
('Swift Swim', 'Boosts the Pokémon\'s Speed stat in rain', 3),
('Chlorophyll', 'Boosts the Pokémon\'s Speed stat in sunshine', 3),
('Illuminate', 'Raises the likelihood of meeting wild Pokémon by illuminating the surroundings', 3),
('Trace', 'When it enters a battle, the Pokémon copies an opposing Pokémon\'s Ability', 3),
('Huge Power', 'Doubles the Pokémon\'s Attack stat', 3),
('Poison Point', 'Contact with the Pokémon may poison the attacker', 3),
('Inner Focus', 'The Pokémon\'s intensely focused, and that protects the Pokémon from flinching', 3),
('Magma Armor', 'The Pokémon is covered with hot magma, which prevents the Pokémon from becoming frozen', 3),
('Water Veil', 'The Pokémon is covered with a water veil, which prevents the Pokémon from getting a burn', 3),
('Magnet Pull', 'Prevents Steel-type Pokémon from escaping using its magnetic force', 3),
('Soundproof', 'Soundproofing of the Pokémon itself gives full immunity to all sound-based moves', 3),
('Rain Dish', 'The Pokémon gradually regains HP in rain', 3),
('Sand Stream', 'The Pokémon summons a sandstorm when it enters a battle', 3),
('Pressure', 'By putting pressure on the opposing Pokémon, it raises their PP usage', 3),
('Thick Fat', 'The Pokémon is protected by a layer of thick fat, which halves the damage taken from Fire- and Ice-type moves', 3),
('Early Bird', 'The Pokémon awakens twice as fast as other Pokémon from sleep', 3),
('Flame Body', 'Contact with the Pokémon may burn the attacker', 3),
('Run Away', 'Enables a sure getaway from wild Pokémon', 3),
('Keen Eye', 'Keen eyes prevent other Pokémon from lowering this Pokémon\'s accuracy', 3),
('Hyper Cutter', 'The Pokémon\'s proud of its powerful pincers. They prevent other Pokémon from lowering its Attack stat', 3),
('Pickup', 'The Pokémon may pick up the item an opposing Pokémon used during a battle. It may pick up items outside of battle, too', 3),
('Truant', 'The Pokémon can\'t use a move the following turn if it uses one', 3),
('Hustle', 'Boosts the Attack stat, but lowers accuracy', 3),
('Cute Charm', 'Contact with the Pokémon may cause infatuation', 3),
('Plus', 'Boosts the Sp. Atk stat of the Pokémon if an ally with the Plus or Minus Ability is also in battle', 3),
('Minus', 'Boosts the Sp. Atk stat of the Pokémon if an ally with the Plus or Minus Ability is also in battle', 3),
('Forecast', 'The Pokémon transforms with the weather to change its type to Water, Fire, or Ice', 3),
('Sticky Hold', 'Items held by the Pokémon are stuck fast and cannot be removed by other Pokémon', 3),
('Shed Skin', 'The Pokémon may heal its own status conditions by shedding its skin', 3),
('Guts', 'It\'s so gutsy that having a status condition boosts the Pokémon\'s Attack stat', 3),
('Marvel Scale', 'The Pokémon\'s marvelous scales boost the Defense stat if it has a status condition', 3),
('Liquid Ooze', 'Oozed liquid has strong stench, which damages attackers using any draining move', 3),
('Overgrow', 'Powers up Grass-type moves when the Pokémon\'s HP is low', 3),
('Blaze', 'Powers up Fire-type moves when the Pokémon\'s HP is low', 3),
('Torrent', 'Powers up Water-type moves when the Pokémon\'s HP is low', 3),
('Swarm', 'Powers up Bug-type moves when the Pokémon\'s HP is low', 3),
('Rock Head', 'Protects the Pokémon from recoil damage', 3),
('Drought', 'Turns the sunlight harsh when the Pokémon enters a battle', 3),
('Arena Trap', 'Prevents opposing Pokémon from fleeing', 3),
('Vital Spirit', 'The Pokémon is full of vitality, and that prevents it from falling asleep', 3),
('White Smoke', 'The Pokémon is protected by its white smoke, which prevents other Pokémon from lowering its stats', 3),
('Pure Power', 'Using its pure power, the Pokémon doubles its Attack stat', 3),
('Shell Armor', 'A hard shell protects the Pokémon from critical hits', 3),
('Air Lock', 'Eliminates the effects of weather', 3),
('Tangled Feet', 'Raises evasion if the Pokémon is confused', 4),
('Motor Drive', 'Boosts its Speed stat if hit by an Electric-type move, instead of taking damage', 4),
('Rivalry', 'Becomes competitive and deals more damage to Pokémon of the same gender, but deals less to Pokémon of the opposite gender', 4),
('Steadfast', 'The Pokémon\'s determination boosts the Speed stat each time the Pokémon flinches', 4),
('Snow Cloak', 'Boosts evasion in a hailstorm', 4),
('Gluttony', 'Makes the Pokémon eat a held Berry when its HP drops to half or less, which is sooner than usual', 4),
('Anger Point', 'The Pokémon is angered when it takes a critical hit, and that maxes its Attack stat', 4),
('Unburden', 'Boosts the Speed stat if the Pokémon\'s held item is used or lost', 4),
('Heatproof', 'The heatproof body of the Pokémon halves the damage from Fire-type moves that hit it', 4),
('Simple', 'The stat changes the Pokémon receives are doubled', 4),
('Dry Skin', 'Restores HP in rain or when hit by Water-type moves. Reduces HP in sunshine, and increases the damage received from Fire-type moves', 4),
('Download', 'Compares an opposing Pokémon\'s Defense and Sp. Def stats before raising its own Attack or Sp. Atk stat—whichever will be more effective', 4),
('Iron Fist', 'Powers up punching moves', 4),
('Poison Heal', 'Restores HP if the Pokémon is poisoned, instead of losing HP', 4),
('Adaptability', 'Powers up moves of the same type as the Pokémon', 4),
('Skill Link', 'Maximizes the number of times multi-strike moves hit', 4),
('Hydration', 'Heals status conditions if it\'s raining', 4),
('Solar Power', 'Boosts the Sp. Atk stat in sunny weather, but HP decreases every turn', 4),
('Quick Feet', 'Boosts the Speed stat if the Pokémon has a status condition', 4),
('Normalize', 'All the Pokémon\'s moves become Normal type. The power of those moves is boosted a little', 4),
('Sniper', 'Powers up moves if they become critical hits when attacking', 4),
('Magic Guard', 'The Pokémon only takes damage from attacks', 4),
('No Guard', 'The Pokémon employs no-guard tactics to ensure incoming and outgoing attacks always land', 4),
('Stall', 'The Pokémon moves after all other Pokémon do', 4),
('Technician', 'Powers up the Pokémon\'s weaker moves', 4),
('Leaf Guard', 'Prevents status conditions in sunny weather', 4),
('Klutz', 'The Pokémon can\'t use any held items', 4),
('Mold Breaker', 'Moves can be used on the target regardless of its Abilities', 4),
('Super Luck', 'The Pokémon is so lucky that the critical-hit ratios of its moves are boosted', 4),
('Aftermath', 'Damages the attacker if it contacts the Pokémon with a finishing hit', 4),
('Anticipation', 'The Pokémon can sense an opposing Pokémon\'s dangerous moves', 4),
('Forewarn', 'When it enters a battle, the Pokémon can tell one of the moves an opposing Pokémon has', 4),
('Unaware', 'When attacking, the Pokémon ignores the target Pokémon\'s stat changes', 4),
('Tinted Lens', 'The Pokémon can use \"not very effective\" moves to deal regular damage', 4),
('Filter', 'Reduces the power of supereffective attacks taken', 4),
('Slow Start', 'For five turns, the Pokémon\'s Attack and Speed stats are halved', 4),
('Scrappy', 'The Pokémon can hit Ghost-type Pokémon with Normal- and Fighting-type moves', 4),
('Storm Drain', 'Draws in all Water-type moves. Instead of being hit by Water-type moves, it boosts its Sp. Atk', 4),
('Ice Body', 'The Pokémon gradually regains HP in a hailstorm', 4),
('Solid Rock', 'Reduces the power of supereffective attacks taken', 4),
('Snow Warning', 'The Pokémon summons a hailstorm when it enters a battle', 4),
('Honey Gather', 'The Pokémon may gather Honey after a battle', 4),
('Frisk', 'When it enters a battle, the Pokémon can check an opposing Pokémon\'s held item', 4),
('Reckless', 'Powers up moves that have recoil damage', 4),
('Multitype', 'Changes the Pokémon\'s type to match the Plate or Z-Crystal it holds', 4),
('Flower Gift', 'Boosts the Attack and Sp. Def stats of itself and allies when it is sunny', 4),
('Bad Dreams', 'Reduces the HP of sleeping opposing Pokémon', 4),
('Pickpocket', 'Steals an item from an attacker that made direct contact', 5),
('Sheer Force', 'Removes additional effects to increase the power of moves when attacking', 5),
('Contrary', 'Makes stat changes have an opposite effect', 5),
('Unnerve', 'Unnerves opposing Pokémon and makes them unable to eat Berries', 5),
('Defiant', 'Boosts the Pokémon\'s Attack stat sharply when its stats are lowered', 5),
('Defeatist', 'Halves the Pokémon\'s Attack and Sp. Atk stats when its HP becomes half or less', 5),
('Cursed Body', 'May disable a move used on the Pokémon', 5),
('Healer', 'Sometimes heals an ally\'s status condition', 5),
('Friend Guard', 'Reduces damage done to allies', 5),
('Weak Armor', 'Physical attacks to the Pokémon lower its Defense stat but sharply raise its Speed stat', 5),
('Heavy Metal', 'Doubles the Pokémon\'s weight', 5),
('Light Metal', 'Halves the Pokémon\'s weight', 5),
('Multiscale', 'Reduces the amount of damage the Pokémon takes when its HP is full', 5),
('Toxic Boost', 'Powers up physical attacks when the Pokémon is poisoned', 5),
('Flare Boost', 'Powers up special attacks when the Pokémon is burned', 5),
('Harvest', 'May create another Berry after one is used', 5),
('Telepathy', 'Anticipates an ally\'s attack and dodges it', 5),
('Moody', 'Raises one stat sharply and lowers another every turn', 5),
('Overcoat', 'Protects the Pokémon from things like sand, hail, and powder', 5),
('Poison Touch', 'May poison a target when the Pokémon makes contact', 5),
('Regenerator', 'Restores a little HP when withdrawn from battle', 5),
('Big Pecks', 'Protects the Pokémon from Defense-lowering effects', 5),
('Sand Rush', 'Boosts the Pokémon\'s Speed stat in a sandstorm', 5),
('Wonder Skin', 'Makes status moves more likely to miss', 5),
('Analytic', 'Boosts move power when the Pokémon moves last', 5),
('Illusion', 'Comes out disguised as the Pokémon in the party\'s last spot', 5),
('Imposter', 'The Pokémon transforms itself into the Pokémon it\'s facing', 5),
('Infiltrator', 'Passes through the opposing Pokémon\'s barrier, substitute, and the like and strikes', 5),
('Mummy', 'Contact with the Pokémon changes the attacker\'s Ability to Mummy', 5),
('Moxie', 'The Pokémon shows moxie, and that boosts the Attack stat after knocking out any Pokémon', 5),
('Justified', 'Being hit by a Dark-type move boosts the Attack stat of the Pokémon, for justice', 5),
('Rattled', 'Dark-, Ghost-, and Bug-type moves scare the Pokémon and boost its Speed stat', 5),
('Magic Bounce', 'Reflects status moves, instead of getting hit by them', 5),
('Sap Sipper', 'Boosts the Attack stat if hit by a Grass-type move, instead of taking damage', 5),
('Prankster', 'Gives priority to a status move', 5),
('Sand Force', 'Boosts the power of Rock-, Ground-, and Steel-type moves in a sandstorm', 5),
('Iron Barbs', 'Inflicts damage to the attacker on contact with iron barbs', 5),
('Zen Mode', 'Changes the Pokémon\'s shape when HP is half or less', 5),
('Victory Star', 'Boosts the accuracy of its allies and itself', 5),
('Turboblaze', 'Moves can be used on the target regardless of its Abilities', 5),
('Teravolt', 'Moves can be used on the target regardless of its Abilities', 5),
('Aroma Veil', 'Protects itself and its allies from attacks that limit their move choices', 6),
('Flower Veil', 'Ally Grass-type Pokémon are protected from status conditions and the lowering of their stats', 6),
('Cheek Pouch', 'Restores HP as well when the Pokémon eats a Berry', 6),
('Protean', 'Changes the Pokémon\'s type to the type of the move it\'s about to use', 6),
('Fur Coat', 'Halves the damage from physical moves', 6),
('Magician', 'The Pokémon steals the held item of a Pokémon it hits with a move', 6),
('Bulletproof', 'Protects the Pokémon from some ball and bomb moves', 6),
('Competitive', 'Boosts the Sp. Atk stat sharply when a stat is lowered', 6),
('Strong Jaw', 'The Pokémon\'s strong jaw boosts the power of its biting moves', 6),
('Refrigerate', 'Normal-type moves become Ice-type moves. The power of those moves is boosted a little', 6),
('Sweet Veil', 'Prevents itself and ally Pokémon from falling asleep', 6),
('Stance Change', 'The Pokémon changes its form to Blade Forme when it uses an attack move, and changes to Shield Forme when it uses King\'s Shield', 6),
('Gale Wings', 'Gives priority to Flying-type moves when the Pokémon\'s HP is full', 6),
('Mega Launcher', 'Powers up aura and pulse moves', 6),
('Grass Pelt', 'Boosts the Pokémon\'s Defense stat in Grassy Terrain', 6),
('Symbiosis', 'The Pokémon passes its item to an ally that has used up an item', 6),
('Tough Claws', 'Powers up moves that make direct contact', 6),
('Pixilate', 'Normal-type moves become Fairy-type moves. The power of those moves is boosted a little', 6),
('Gooey', 'Contact with the Pokémon lowers the attacker\'s Speed stat', 6),
('Aerilate', 'Normal-type moves become Flying-type moves. The power of those moves is boosted a little', 6),
('Parental Bond', 'Parent and child each attacks', 6),
('Dark Aura', 'Powers up each Pokémon\'s Dark-type moves', 6),
('Fairy Aura', 'Powers up each Pokémon\'s Fairy-type moves', 6),
('Aura Break', 'The effects of \"Aura\" Abilities are reversed to lower the power of affected moves', 6),
('Primordial Sea', 'The Pokémon changes the weather to nullify Fire-type attacks', 6),
('Desolate Land', 'The Pokémon changes the weather to nullify Water-type attacks', 6),
('Delta Stream', 'The Pokémon changes the weather to eliminate all of the Flying type\'s weaknesses', 6),
('Stamina', 'Boosts the Defense stat when hit by an attack', 7),
('Wimp Out', 'The Pokémon cowardly switches out when its HP becomes half or less', 7),
('Emergency Exit', 'The Pokémon, sensing danger, switches out when its HP becomes half or less', 7),
('Water Compaction', 'Boosts the Pokémon\'s Defense stat sharply when hit by a Water-type move', 7),
('Merciless', 'The Pokémon\'s attacks become critical hits if the target is poisoned', 7),
('Shields Down', 'When its HP becomes half or less, the Pokémon\'s shell breaks and it becomes aggressive', 7),
('Stakeout', 'Doubles the damage dealt to the target\'s replacement if the target switches out', 7),
('Water Bubble', 'Lowers the power of Fire-type moves done to the Pokémon and prevents the Pokémon from getting a burn', 7),
('Steelworker', 'Powers up Steel-type moves', 7),
('Berserk', 'Boosts the Pokémon\'s Sp. Atk stat when it takes a hit that causes its HP to become half or less', 7),
('Slush Rush', 'Boosts the Pokémon\'s Speed stat in a hailstorm', 7),
('Long Reach', 'The Pokémon uses its moves without making contact with the target', 7),
('Liquid Voice', 'All sound-based moves become Water-type moves', 7),
('Triage', 'Gives priority to a healing move', 7),
('Galvanize', 'Normal-type moves become Electric-type moves. The power of those moves is boosted a little', 7),
('Surge Surfer', 'Doubles the Pokémon\'s Speed stat on Electric Terrain', 7),
('Schooling', 'When it has a lot of HP, the Pokémon forms a powerful school. It stops schooling when its HP is low', 7),
('Disguise', 'Once per battle, the shroud that covers the Pokémon can protect it from an attack', 7),
('Battle Bond', 'Defeating an opposing Pokémon strengthens the Pokémon\'s bond with its Trainer, and it becomes Ash-Greninja. Water Shuriken gets more powerful', 7),
('Power Construct', 'Other Cells gather to aid when its HP becomes half or less. Then the Pokémon changes its form to Complete Forme', 7),
('Corrosion', 'The Pokémon can poison the target even if it\'s a Steel or Poison type', 7),
('Comatose', 'It\'s always drowsing and will never wake up. It can attack without waking up', 7),
('Queenly Majesty', 'Its majesty pressures the opposing Pokémon, making it unable to attack using priority moves', 7),
('Innards Out', 'Damages the attacker landing the finishing hit by the amount equal to its last HP', 7),
('Dancer', 'When another Pokémon uses a dance move, it can use a dance move following it regardless of its Speed', 7),
('Battery', 'Powers up ally Pokémon\'s special moves', 7),
('Fluffy', 'Halves the damage taken from moves that make direct contact, but doubles that of Fire-type moves', 7),
('Dazzling', 'Surprises the opposing Pokémon, making it unable to attack using priority moves', 7),
('Soul-Heart', 'Boosts its Sp. Atk stat every time a Pokémon faints', 7),
('Tangling Hair', 'Contact with the Pokémon lowers the attacker\'s Speed stat', 7),
('Receiver', 'The Pokémon copies the Ability of a defeated ally', 7),
('Power of Alchemy', 'The Pokémon copies the Ability of a defeated ally', 7),
('Beast Boost', 'The Pokémon boosts its most proficient stat each time it knocks out a Pokémon', 7),
('RKS System', 'Changes the Pokémon\'s type to match the memory disc it holds', 7),
('Electric Surge', 'Turns the ground into Electric Terrain when the Pokémon enters a battle', 7),
('Psychic Surge', 'Turns the ground into Psychic Terrain when the Pokémon enters a battle', 7),
('Misty Surge', 'Turns the ground into Misty Terrain when the Pokémon enters a battle', 7),
('Grassy Surge', 'Turns the ground into Grassy Terrain when the Pokémon enters a battle', 7),
('Full Metal Body', 'Prevents other Pokémon\'s moves or Abilities from lowering the Pokémon\'s stats', 7),
('Shadow Shield', 'Reduces the amount of damage the Pokémon takes while its HP is full', 7),
('Prism Armor', 'Reduces the power of supereffective attacks taken', 7),
('Neuroforce', 'Powers up moves that are super effective', 7)